// exeception handling

/* 
The execution of program is terminated 
abnormorly
*/

void main() {
  try {} catch (e) {}
}
